/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#faf8ff",
        foreground: "hsl(var(--foreground))",
        "surface-tint": "#0053db",
        "surface-container-lowest": "#ffffff",
        "outline": "#737686",
        "on-tertiary-fixed": "#00184a",
        "on-surface": "#131b2e",
        "on-primary-container": "#eeefff",
        "on-tertiary": "#ffffff",
        "surface-container": "#eaedff",
        "surface": "#faf8ff",
        "on-error-container": "#93000a",
        "secondary-container": "#da3339",
        "on-primary-fixed": "#00174b",
        "on-secondary-container": "#fffbff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed": "#410005",
        "primary": "#004ac6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed": "#dbe1ff",
        "on-background": "#131b2e",
        "secondary-fixed-dim": "#ffb3ae",
        "secondary": "#b61524",
        "secondary-fixed": "#ffdad7",
        "on-tertiary-container": "#eeefff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed-variant": "#003ea6",
        "surface-variant": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "inverse-primary": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed-dim": "#b3c5ff",
        "tertiary-container": "#2864e6",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "on-secondary": "#ffffff",
        "primary-container": "#2563eb",
        "inverse-surface": "#283044",
        "surface-container-highest": "#dae2fd",
        "tertiary": "#004bc4",
        "on-secondary-fixed-variant": "#930016",
        "tertiary-fixed": "#dbe1ff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'premium': '0 10px 30px -10px rgba(0, 74, 198, 0.15), 0 4px 10px -5px rgba(0, 0, 0, 0.05)',
        'premium-hover': '0 20px 40px -15px rgba(0, 74, 198, 0.25), 0 8px 15px -10px rgba(0, 0, 0, 0.1)',
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
        'inner-glow': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.1)',
      },
      backdropBlur: {
        'xs': '2px',
        'premium': '20px',
        'ultra': '40px',
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out forwards',
        'fade-in-up': 'fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-right': 'slide-in-right 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        }
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
}
  },
  plugins: [],
}