using System;

namespace Application.DTOs.Booking;

public class BookingDocumentResponse
{
    public Guid Id { get; set; }
    public Guid BookingId { get; set; }
    public string FileName { get; set; } = string.Empty;
    public string FilePath { get; set; } = string.Empty;
    public long FileSize { get; set; }
    public string ContentType { get; set; } = string.Empty;
    public DateTime UploadedAt { get; set; }
    public string DownloadUrl { get; set; } = string.Empty; // Will be generated by controller
}